# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  ImageName: 'yacinezighem/simpleapi:$(Build.BuildId)'  
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*test/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

  # Build and Push
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: DockerTest
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerTest
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: yacinezighem
    tags: |
      tag1
      tag2



